### ISSUE TITLE
Timestamp sample fails with IllegalStateException when using Spring Boot M7

### ISSUE THREAD

**Issue by springframeworkguru** [spring-cloud/spring-cloud-task#374]
Using sample from GitHub repo for Spring Cloud Task under: 'spring-cloud-task-samples/timestamp' which is on Spring Boot M5. 

running mvn spring-boot:run completes normally with Spring Boot M5.

When the Spring Boot version is updated to M7, the following exception is thrown:

```
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::             (v2.0.0.M7)

2018-01-12 12:21:02.900  INFO 16541 --- [           main] o.s.c.task.timestamp.TaskApplication     : Starting TaskApplication on ip-10-0-1-4.eu-west-1.compute.internal with PID 16541 (/Users/jt/tmp/cloudtask/spring-cloud-task/spring-cloud-task-samples/timestamp/target/classes started by jt in /Users/jt/tmp/cloudtask/spring-cloud-task/spring-cloud-task-samples/timestamp)
2018-01-12 12:21:02.904 DEBUG 16541 --- [           main] o.s.c.task.timestamp.TaskApplication     : Running with Spring Boot v2.0.0.M7, Spring v5.0.2.RELEASE
2018-01-12 12:21:02.904  INFO 16541 --- [           main] o.s.c.task.timestamp.TaskApplication     : No active profile set, falling back to default profiles: default
2018-01-12 12:21:02.953  INFO 16541 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@1e4e87d7: startup date [Fri Jan 12 12:21:02 EST 2018]; root of context hierarchy
2018-01-12 12:21:03.562  INFO 16541 --- [           main] com.zaxxer.hikari.HikariDataSource       : testdb - Starting...
2018-01-12 12:21:03.917  INFO 16541 --- [           main] com.zaxxer.hikari.HikariDataSource       : testdb - Start completed.
2018-01-12 12:21:03.928 DEBUG 16541 --- [           main] o.s.c.t.c.SimpleTaskConfiguration        : Using org.springframework.cloud.task.configuration.DefaultTaskConfigurer TaskConfigurer
2018-01-12 12:21:03.929 DEBUG 16541 --- [           main] o.s.c.t.c.DefaultTaskConfigurer          : No EntityManager was found, using DataSourceTransactionManager
2018-01-12 12:21:04.054 DEBUG 16541 --- [           main] o.s.c.t.r.s.TaskRepositoryInitializer    : Initializing task schema for h2 database
2018-01-12 12:21:04.057  INFO 16541 --- [           main] o.s.jdbc.datasource.init.ScriptUtils     : Executing SQL script from class path resource [org/springframework/cloud/task/schema-h2.sql]
2018-01-12 12:21:04.088  INFO 16541 --- [           main] o.s.jdbc.datasource.init.ScriptUtils     : Executed SQL script from class path resource [org/springframework/cloud/task/schema-h2.sql] in 31 ms.
2018-01-12 12:21:04.302  INFO 16541 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-01-12 12:21:04.303  INFO 16541 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'dataSource' has been autodetected for JMX exposure
2018-01-12 12:21:04.306  INFO 16541 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located MBean 'dataSource': registering with JMX server as MBean [com.zaxxer.hikari:name=dataSource,type=HikariDataSource]
2018-01-12 12:21:04.311  INFO 16541 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2018-01-12 12:21:04.337 DEBUG 16541 --- [           main] o.s.c.t.r.support.SimpleTaskRepository   : Creating: TaskExecution{executionId=0, parentExecutionId=null, exitCode=null, taskName='Demo Timestamp Task', startTime=Fri Jan 12 12:21:04 EST 2018, endTime=null, exitMessage='null', externalExecutionId='null', errorMessage='null', arguments=[]}
2018-01-12 12:21:04.351 DEBUG 16541 --- [           main] o.s.c.t.r.support.SimpleTaskRepository   : Updating: TaskExecution with executionId=1 with the following {exitCode=0, endTime=Fri Jan 12 12:21:04 EST 2018, exitMessage='null', errorMessage='null'}
2018-01-12 12:21:04.354  INFO 16541 --- [           main] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@1e4e87d7: startup date [Fri Jan 12 12:21:02 EST 2018]; root of context hierarchy
2018-01-12 12:21:04.355  INFO 16541 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
2018-01-12 12:21:04.356  INFO 16541 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2018-01-12 12:21:04.356  INFO 16541 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans
2018-01-12 12:21:04.357  INFO 16541 --- [           main] com.zaxxer.hikari.HikariDataSource       : testdb - Shutdown initiated...
2018-01-12 12:21:04.359  INFO 16541 --- [           main] com.zaxxer.hikari.HikariDataSource       : testdb - Shutdown completed.
2018-01-12 12:21:04.360  INFO 16541 --- [           main] o.s.c.task.timestamp.TaskApplication     : Started TaskApplication in 2.005 seconds (JVM running for 6.097)
2018-01-12 12:21:04.362  INFO 16541 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-01-12 12:21:04.367 ERROR 16541 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext@1e4e87d7 has been closed already
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1069) ~[spring-context-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1193) ~[spring-context-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:765) [spring-boot-2.0.0.M7.jar:2.0.0.M7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) [spring-boot-2.0.0.M7.jar:2.0.0.M7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1245) [spring-boot-2.0.0.M7.jar:2.0.0.M7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1233) [spring-boot-2.0.0.M7.jar:2.0.0.M7]
	at org.springframework.cloud.task.timestamp.TaskApplication.main(TaskApplication.java:51) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:496) [spring-boot-maven-plugin-2.0.0.M7.jar:2.0.0.M7]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

```

**Comment by springframeworkguru** [comment]
Cool - thanks for the quick response!

**Comment by lnhrdt** [comment]
I ran across this today as well. In case it saves any time for anyone else running into this, the issue seems to only affect Spring Boot M7. Spring Cloud Task is working fine up to M6.

Looking forward to the next Spring Boot Milestone or RC!

**Comment by sabbyanandan** [comment]
Closing this in favor of #360.
