### ISSUE TITLE
BeanCreationException handling  during  task startup

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud/spring-cloud-task#398]
Hello
If my task uses validated properties, like 

```java
@ConfigurationProperties("prefix")
@Data
public class MyTaskProperties   {
   @NotEmpty
   private  String someConfigValue;
}
```

and `prefix.someConfigValue` was not provided when running the task application, the task fails to start (this is **OK**), but this is not recorded in DB, neither `start` nor `end` timestamp.

This also causing `NullPoinetException` when openning  **Jobs** tab in SCDF dashboard UI (when th is task is part of CTR graph ):

````
   2018-03-01T13:35:27.52+0200 [RTR/0] OUT
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.springframework.cloud.dataflow.server.controller.JobExecutionController.list(JobExecutionController.java:91) ~[spring-cloud-dataflow-server-core-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.23.jar!/:8.5.23]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
````

**Comment by mminella** [comment]
If the `ApplicationContext` does not start (as this is the case I believe), we wouldn't be able to record the attempt in a db.  That being said, there is an associated issue in SCDF (https://github.com/spring-cloud/spring-cloud-dataflow/issues/1822) for the NPE.

**Comment by jvmlet** [comment]
This issue can cause CTR to hang forever, may be even if timeout is specified for task execution...

**Comment by jvmlet** [comment]
May be CTR should at least record the start attempt to not enter the infinite loop and be able to treat task as failed after timeout?

**Comment by cppwfs** [comment]
As to the CTR hanging issue, I created an issue to track information:  https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/30.  I'll take a peak at it.

**Comment by sabbyanandan** [comment]
Since the improvements will be addressed in CTR directly, I will close this issue.
