### ISSUE TITLE
Add Configurable retry for when Task updates Task_Execution table.

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-task#411]
Add Spring-retry around methods that update the datastore in the SimpleTaskRepository.   These should be configurable for number of retries as well as the waitTime between each retry.

**Comment by mminella** [comment]
I'm not sure I agree with this.  We should understand why the retry is needed.  Just blindly adding it doesn't make sense to me.

**Comment by venkatasreekanth** [comment]
I guess I am late to this party but this would help in situations where network issues exist only for a few minutes. We have setup network monitoring for months to get the root cause of this issue. Somehow we have failed for reasons  beyond our control.

Below are the logs that will hopefully convince you to add retry and wait time.
2019-01-28 15:40:10.616  WARN 24614 --- [ck-leadership-1] o.s.jdbc.support.SQLErrorCodesFactory    : Error while extracting database name - falling back to empty error codes

org.springframework.jdbc.support.MetaDataAccessException: Could not get Connection for extracting meta-data; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
        at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:328) ~[spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:356) ~[spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.jdbc.support.SQLErrorCodesFactory.getErrorCodes(SQLErrorCodesFactory.java:214) ~[spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.setDataSource(SQLErrorCodeSQLExceptionTranslator.java:136) [spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.<init>(SQLErrorCodeSQLExceptionTranslator.java:99) [spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.jdbc.support.JdbcAccessor.getExceptionTranslator(JdbcAccessor.java:122) [spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1402) [spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:620) [spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850) [spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:905) [spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:915) [spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.integration.jdbc.lock.DefaultLockRepository.deleteExpired(DefaultLockRepository.java:177) [spring-integration-jdbc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.integration.jdbc.lock.DefaultLockRepository.acquire(DefaultLockRepository.java:157) [spring-integration-jdbc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.integration.jdbc.lock.JdbcLockRegistry$JdbcLock.doLock(JdbcLockRegistry.java:204) [spring-integration-jdbc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.integration.jdbc.lock.JdbcLockRegistry$JdbcLock.tryLock(JdbcLockRegistry.java:185) [spring-integration-jdbc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.integration.support.leader.LockRegistryLeaderInitiator$LeaderSelector.call(LockRegistryLeaderInitiator.java:369) [spring-integration-core-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.integration.support.leader.LockRegistryLeaderInitiator$LeaderSelector.call(LockRegistryLeaderInitiator.java:343) [spring-integration-core-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81) ~[spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:319) ~[spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        ... 20 common frames omitted
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96) ~[HikariCP-2.7.9.jar!/:na]
        at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:151) ~[spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115) ~[spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78) ~[spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        ... 21 common frames omitted

**Comment by venkatasreekanth** [comment]
I know it has been rejected before but I would like to try and convince you, again. No network is perpetually immune to issues, there should some amount recovery/retry built into the process. This becomes especially important when micro batching is done and done 24x7x365. Spring Batch itself has retry logic for the job but not for itself when writing to task_lock millions of times(kind of doesn't make sense to me). @mminella himself talks about retry in his video lecture series "learning spring batch". I would like further strengthen the argument with this article https://en.wikipedia.org/wiki/Fallacies_of_distributed_computing

![image](https://user-images.githubusercontent.com/7682333/60824829-fa0b5800-a16f-11e9-9411-0a278bc140d4.png)
