### ISSUE TITLE
Task lock isn't cleared but the job ends

### ISSUE THREAD

**Issue by venkatasreekanth** [spring-cloud/spring-cloud-task#503]
I have the following configuration on the batch job

spring.cloud.task.singleInstanceEnabled=true

Sometimes the job appears to complete successfully but the lock isn't cleared. All subsequent jobs fail as a result. I have not been able to reproduce the issue locally and no error is reported in the logs.

```
2019-01-08 17:35:06.153 INFO 12282 --- [ main] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@67117f44: startup date [Tue Jan 08 17:35:02 CST 2019]; root of context hierarchy
2019-01-08 17:35:06.155 INFO 12282 --- [ main] o.s.c.support.DefaultLifecycleProcessor : Stopping beans in phase 0
2019-01-08 17:35:06.156 INFO 12282 --- [ main] o.s.i.endpoint.EventDrivenConsumer : Removing {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2019-01-08 17:35:06.156 INFO 12282 --- [ main] o.s.i.channel.PublishSubscribeChannel : Channel 'application.errorChannel' has 0 subscriber(s).
2019-01-08 17:35:06.156 INFO 12282 --- [ main] o.s.i.endpoint.EventDrivenConsumer : stopped _org.springframework.integration.errorLogger
2019-01-08 17:35:06.156 INFO 12282 --- [ main] o.s.s.c.ThreadPoolTaskScheduler : Shutting down ExecutorService 'taskScheduler'
2019-01-08 17:35:06.157 INFO 12282 --- [ main] o.s.j.e.a.AnnotationMBeanExporter : Unregistering JMX-exposed beans on shutdown
2019-01-08 17:35:06.157 INFO 12282 --- [ main] o.s.j.e.a.AnnotationMBeanExporter : Unregistering JMX-exposed beans
2019-01-08 17:35:06.157 INFO 12282 --- [ main] o.a.k.clients.producer.KafkaProducer : [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
2019-01-08 17:35:06.160 WARN 12282 --- [@xxxxx] o.a.k.c.security.kerberos.KerberosLogin : [Principal=xxxxxxxxxxx]: TGT renewal thread has been interrupted and will exit.
2019-01-08 17:35:06.161 INFO 12282 --- [ main] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Shutdown initiated...
2019-01-08 17:35:06.165 INFO 12282 --- [ main] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Shutdown completed.
2019-01-08 17:35:06.166 WARN 12282 --- [ck-leadership-1] com.zaxxer.hikari.pool.PoolBase : HikariPool-1 - Failed to validate connection ConnectionID:2 ClientConnectionId: f57e6cb8-d3cf-4bb8-b6d1-6cfba5aef264 (The connection is closed.)
2019-01-08 17:35:06.167 INFO 12282 --- [ck-leadership-1] o.s.integration.leader.DefaultCandidate : DefaultCandidate{role=pim_batch_task, id=17303} leadership has been revoked: LockContext{role=pim_batch_task, id=17303, isLeader=false}
```

There is another situation where it complains of socket closed and fails to clear the lock. The issue here is that the job never complains that is failed to start a job because of socket closed. I am guessing that may be during the clearing of the lock retry logic may be missing. 

below are the logs for socket closed

```
2019-01-07 11:10:11.542  INFO 12108 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-01-07 11:10:11.546  WARN 12108 --- [ck-leadership-1] com.zaxxer.hikari.pool.ProxyConnection   : HikariPool-1 - Connection ConnectionID:1 ClientConnectionId: 71d2bea6-38f7-416f-a0a7-bccd5e5c2f66 marked as broken because of SQLSTATE(08S01), ErrorCode(0)

com.microsoft.sqlserver.jdbc.SQLServerException: Socket closed
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2435) ~[mssql-jdbc-6.2.2.jre8.jar!/:na]
        at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:1991) ~[mssql-jdbc-6.2.2.jre8.jar!/:na]
        at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6310) ~[mssql-jdbc-6.2.2.jre8.jar!/:na]
        at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7545) ~[mssql-jdbc-6.2.2.jre8.jar!/:na]
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:465) ~[mssql-jdbc-6.2.2.jre8.jar!/:na]
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:409) ~[mssql-jdbc-6.2.2.jre8.jar!/:na]
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7151) ~[mssql-jdbc-6.2.2.jre8.jar!/:na]
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2478) ~[mssql-jdbc-6.2.2.jre8.jar!/:na]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:219) ~[mssql-jdbc-6.2.2.jre8.jar!/:na]
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:199) ~[mssql-jdbc-6.2.2.jre8.jar!/:na]
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:356) ~[mssql-jdbc-6.2.2.jre8.jar!/:na]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-2.7.9.jar!/:na]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) [HikariCP-2.7.9.jar!/:na]
        at org.springframework.jdbc.core.JdbcTemplate.lambda$update$0(JdbcTemplate.java:855) [spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:605) [spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850) [spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:905) [spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:915) [spring-jdbc-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
        at org.springframework.integration.jdbc.lock.DefaultLockRepository.deleteExpired(DefaultLockRepository.java:177) ~[spring-integration-jdbc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.integration.jdbc.lock.DefaultLockRepository.acquire(DefaultLockRepository.java:157) ~[spring-integration-jdbc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.integration.jdbc.lock.JdbcLockRegistry$JdbcLock.doLock(JdbcLockRegistry.java:204) ~[spring-integration-jdbc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.integration.jdbc.lock.JdbcLockRegistry$JdbcLock.tryLock(JdbcLockRegistry.java:185) ~[spring-integration-jdbc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.integration.support.leader.LockRegistryLeaderInitiator$LeaderSelector.call(LockRegistryLeaderInitiator.java:369) ~[spring-integration-core-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.integration.support.leader.LockRegistryLeaderInitiator$LeaderSelector.call(LockRegistryLeaderInitiator.java:343) ~[spring-integration-core-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191] Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_191]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_191]
        at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[na:1.8.0_191]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_191]
        at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:1981) ~[mssql-jdbc-6.2.2.jre8.jar!/:na]
        ... 26 common frames omitted
```

I have also added the below config to the dataflow server properties, but seems to have not effect

spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.connection-timeout=600000

**Comment by sabbyanandan** [comment]
We are unable to reproduce it. If you have a sample that does, please share it, we can reopen then.
