### ISSUE TITLE
Spring cloud task application does not run underlying batchjob on its own

### ISSUE THREAD

**Issue by jobas2007** [spring-cloud/spring-cloud-task#594]
In reference to ‘Spring Boot Start Application Error when trying to configure seperate datasource for spring batch schema and application #585’ , when run the application which is task enabled , the underlying batch job does not run on its own . Is there a way to have “job” run on its own ? 

Note : my test app uses two data sources ( as github link is in #585)  , the spring batch enabled property is set to false . This is causing issue when trying to work with spring cloud data flow server , where the Task app runs , but underlying job does not run .

2) already submitted issue with spring data flow as well

**Comment by jobas2007** [comment]
Apologies for typo in title , it is underlying “batch job “

**Comment by jobas2007** [comment]
Further tried option of enabling Spring Batch Job Enabled into the Spring Batch/Task Application, (by spring.batch.job.enabled=true), which does seems to at least trigger the batch jobs when "Task" is launched from Spring Cloud Data Flow, but then got below exception (which appear to be related to some kind of transaction locking) :

2019-04-14 11:54:30,753 ERROR org.springframework.boot.SpringApplication [main] Application run failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:816)
at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
at com.db.sts.marketdata.MarketDataApplication.main(MarketDataApplication.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.springframework.dao.CannotSerializeTransactionException: PreparedStatementCallback; SQL [INSERT into BATCH_JOB_INSTANCE(JOB_INSTANCE_ID, JOB_NAME, JOB_KEY, VERSION) values (?, ?, ?, ?)]; ORA-08177: can't serialize access for this transaction
; nested exception is java.sql.SQLException: ORA-08177: can't serialize access for this transaction

at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:270)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1442)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:632)
at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:861)
at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:916)
at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:921)
at org.springframework.batch.core.repository.dao.JdbcJobInstanceDao.createJobInstance(JdbcJobInstanceDao.java:117)
at org.springframework.batch.core.repository.support.SimpleJobRepository.createJobExecution(SimpleJobRepository.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.batch.core.repository.support.AbstractJobRepositoryFactoryBean$1.invoke(AbstractJobRepositoryFactoryBean.java:181)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
at com.sun.proxy.$Proxy77.createJobExecution(Unknown Source)
at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:134)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:127)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
at com.sun.proxy.$Proxy75.run(Unknown Source)
at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.execute(JobLauncherCommandLineRunner.java:214)
at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.executeLocalJobs(JobLauncherCommandLineRunner.java:186)
at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.launchJobFromProperties(JobLauncherCommandLineRunner.java:172)
at org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.run(JobLauncherCommandLineRunner.java:166)
at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813)
... 13 common frames omitted
Caused by: java.sql.SQLException: ORA-08177: can't serialize access for this transaction

at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1044)
at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1329)
at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584)
at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3665)
at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1352)
at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
at org.springframework.jdbc.core.JdbcTemplate.lambda$update$0(JdbcTemplate.java:866)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:616)
... 49 common frames omitted

**Comment by cppwfs** [comment]
I did a quick scan of your application.   There are some issues:
1) Spring Cloud Tasks and batch are ephemeral applications, and I see you have included spring web which is is a long running process.   You should not mix the two.  (so please remove the spring web component).
2) When trying to build your project the tests fail.   I'm assuming you are skipping the tests.   

1) Can you provide the arguments that you are passing into the project (cleanse of passwords and urls of course) that you are using?
2) Out of curiosity have you looked at this sample app that shows how to use multiple data sources? https://github.com/spring-cloud/spring-cloud-task/tree/master/spring-cloud-task-samples/multiple-datasources

**Comment by cppwfs** [comment]
I was just awarded with some good information ;-).   The spring-web  and controller you have in your app are ok to leave.  Sorry for the confusion.

**Comment by jobas2007** [comment]
Hello,
Thanks for reply.

Please note that to run the application on github (out of box), you will need a mysql database with 2 schema
1) dataflow (empty schema is fine)
2)my_app_db (with single table 'User')
DDL - 
CREATE TABLE `my_app_db`.`User` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `dept` VARCHAR(45) NULL,
  `salary` INT NULL,
  PRIMARY KEY (`id`));

--------------------------------------------
And then update the username/password etc in the application.properties accordingly. I tested the latest for github and junit ran fine (with above).

Again , the test app is mainly to outline approach, it may need minor adjustments to make it work at your end.

And yes already followed 
https://github.com/spring-cloud/spring-cloud-task/tree/master/spring-cloud-task-samples/multiple-datasources

Thanks once again for continued assistance.


> I did a quick scan of your application. There are some issues:
> 
> 1. Spring Cloud Tasks and batch are ephemeral applications, and I see you have included spring web which is is a long running process.   You should not mix the two.  (so please remove the spring web component).
> 2. When trying to build your project the tests fail.   I'm assuming you are skipping the tests.
> 3. Can you provide the arguments that you are passing into the project (cleanse of passwords and urls of course) that you are using?
> 4. Out of curiosity have you looked at this sample app that shows how to use multiple data sources? https://github.com/spring-cloud/spring-cloud-task/tree/master/spring-cloud-task-samples/multiple-datasources

**Comment by cppwfs** [comment]
Just to clarify.  Running this application from the command line works correct?   
As I just tested below:  i.e.
```
2019-04-16 09:41:34.053  INFO 57311 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2019-04-16 09:41:34.060  INFO 57311 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 7 ms
2019-04-16 09:41:34.135  INFO 57311 --- [nio-8080-exec-1] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=ETL-Load]] launched with the following parameters: [{time=1555422094079}]
2019-04-16 09:41:34.145  INFO 57311 --- [nio-8080-exec-1] o.s.c.t.b.l.TaskBatchExecutionListener   : The job execution id 3 was run within the task execution 50
2019-04-16 09:41:34.175  INFO 57311 --- [nio-8080-exec-1] o.s.batch.core.job.SimpleStepHandler     : Executing step: [ETL-File-Load]
Converted from [001] to [Technology]
Converted from [002] to [Operations]
Converted from [003] to [Accounts]
Data Saved For Users:[User [id=1, name=Peter, dept=Technology, salary=12000], User [id=2, name=Sam, dept=Operations, salary=13000], User [id=3, name=Ryan, dept=Accounts, salary=10000]]
Hibernate: select user0_.id as id1_0_0_, user0_.dept as dept2_0_0_, user0_.name as name3_0_0_, user0_.salary as salary4_0_0_ from User user0_ where user0_.id=?
Hibernate: select user0_.id as id1_0_0_, user0_.dept as dept2_0_0_, user0_.name as name3_0_0_, user0_.salary as salary4_0_0_ from User user0_ where user0_.id=?
Hibernate: select user0_.id as id1_0_0_, user0_.dept as dept2_0_0_, user0_.name as name3_0_0_, user0_.salary as salary4_0_0_ from User user0_ where user0_.id=?
Hibernate: insert into User (dept, name, salary, id) values (?, ?, ?, ?)
Hibernate: insert into User (dept, name, salary, id) values (?, ?, ?, ?)
Hibernate: insert into User (dept, name, salary, id) values (?, ?, ?, ?)
2019-04-16 09:41:34.334  INFO 57311 --- [nio-8080-exec-1] o.s.b.c.l.support.SimpleJobLauncher      : Job: [SimpleJob: [name=ETL-Load]] completed with the following parameters: [{time=1555422094079}] and the following status: [COMPLETED]
JobExecution: COMPLETED
```
It only fails from dataflow, correct?

**Comment by cppwfs** [comment]
If you look at your application.properties you have the spring.batch.job.enabled set to false.  Set it to true and the batch job fires.    i.e. here: https://github.com/jobas2007/spring_proj/blob/master/src/main/resources/application.properties#L3

**Comment by jobas2007** [comment]
Hi Glenn,

Thanks for response . But when we do the same, the issue is that (atleast
with Oracle 11.2) , see some kind of transaction locking when a task / job
is trigger from data flow . Basically trying to understand how things are
wired between data flow , task and batch jobs and having clarity
surrounding it could give a good idea of how things are managed in the
workflow ?

**Comment by cppwfs** [comment]
Let's go back to my first question:
Does it work if you launch the app from the command-line?  Or does it fail there as well? 
Also, why are you using `EnableTransactionManagement` ?  I didn't see a need for it, unless I'm missing something.

**Comment by cppwfs** [comment]
Just checking in.  Any progress?

**Comment by jobas2007** [comment]
> Let's go back to my first question:
> Does it work if you launch the app from the command-line? Or does it fail there as well?
> Also, why are you using `EnableTransactionManagement` ? I didn't see a need for it, unless I'm missing something.

Yes it works, when I set the spring.batch.job.enabled=true (still trying to dig deeper into understanding what does this property really does internally). I also removed the @EnableTransactionManagement.

Now still trying to make this Spring Batch / Task app work with dataflow, where atleast with Oracle 11.2 saw some transaction locking etc with 2 datasources. Appreciate if you can try the same at your end?

**Comment by cppwfs** [comment]
What Transaction Isolation level are you using?

**Comment by jobas2007** [comment]
> What Transaction Isolation level are you using?

I am using the default and now i know where you are going with htis. Yes, I can override the BatchConfigurer to change that and give it a try.

But keeping that aside, (and not using Spring Cloud Data Flow) is it possible to somehow define a Spring Cloud "Task" inside the same spring batch application, and associate/map it with "particular" Jobs, and then upon "execution" automatically triggers all associated underlying Jobs? How to Trigger the Task (outside scdf) is another question? 

Appreciate any help as always.

**Comment by sabbyanandan** [comment]
Questions like this are better to be discussed in Gitter. We use GH for feature requests and/or bug reports.
