### ISSUE TITLE
Spring Batch 'jobs must not be null nor empty' Error

### ISSUE THREAD

**Issue by umutcann** [spring-cloud/spring-cloud-task#772]
Hi there,

I'm running Spring batch apps on Openshift using SCDF.

I'm getting error during Spring Batch starting-up like below.

What is the main reason of that?

`2021-03-08 12:06:54.629 ERROR [ark-batch-template,,] 1    [main] c.g.a.b.c.l.StartupAppListener                 - StartupAppListener: ApplicationFailedEvent:exception {}Failed to instantiate [org.springframework.cloud.task.batch.configuration.TaskJobLauncherCommandLineRunnerFactoryBean]: Factory method 'jobLauncherCommandLineRunner' threw exception; nested exception is java.lang.IllegalArgumentException: jobs must not be null nor empty
org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.task.batch.configuration.TaskJobLauncherCommandLineRunnerFactoryBean]: Factory method 'jobLauncherCommandLineRunner' threw exception; nested exception is java.lang.IllegalArgumentException: jobs must not be null nor empty
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:607) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:826) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at com.garanti.domain.subdomain.arkbatchtemplate.app.SampleApplication.main(SampleApplication.java:20) ~[classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47) ~[ark-batch-template-app-2.1.0-alpha.1.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:86) ~[ark-batch-template-app-2.1.0-alpha.1.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) ~[ark-batch-template-app-2.1.0-alpha.1.jar:?]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) ~[ark-batch-template-app-2.1.0-alpha.1.jar:?]
Caused by: java.lang.IllegalArgumentException: jobs must not be null nor empty
	`

**Comment by cppwfs** [comment]
When I see this error it means that JobLauncherCommandLineRunner could not find any jobs in the ApplicationContext.   This usually means 
* That the Configuration class has not been annotated with `@Configuration`
* The bean declaration is missing the `@Bean` Annotation
* The Job is not in the class path.

**Comment by umutcann** [comment]
Yes @cppwfs, you are right.

It was my fault. Thanks for your help.
