### ISSUE TITLE
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT JOB_INSTANCE_ID, JOB_NAME from BATCH_JOB_INSTANCE where JOB_NAME = ? and JOB_KEY = ?]

### ISSUE THREAD

**Issue by nicolasduminil** [spring-cloud/spring-cloud-task#790]
Hi,

Running the demo with the following command:

    java -jar target/partitioned-job.jar --spring.profiles.active=master
raises the following exception:

      Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "BATCH_JOB_INSTANCE" not found; SQL statement:
       SELECT JOB_INSTANCE_ID, JOB_NAME from BATCH_JOB_INSTANCE where JOB_NAME = ? and JOB_KEY = ? [42102-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:453) ~[h2-1.4.200.jar!/:na]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2-1.4.200.jar!/:na]
        at org.h2.message.DbException.get(DbException.java:205) ~[h2-1.4.200.jar!/:na]
        at org.h2.message.DbException.get(DbException.java:181) ~[h2-1.4.200.jar!/:na]
        at org.h2.command.Parser.readTableOrView(Parser.java:7628) ~[h2-1.4.200.jar!/:na]
        at org.h2.command.Parser.readTableFilter(Parser.java:1970) ~[h2-1.4.200.jar!/:na]
        at org.h2.command.Parser.parseSelectFromPart(Parser.java:2827) ~[h2-1.4.200.jar!/:na]
        at org.h2.command.Parser.parseSelect(Parser.java:2959) ~[h2-1.4.200.jar!/:na]
        at org.h2.command.Parser.parseQuerySub(Parser.java:2817) ~[h2-1.4.200.jar!/:na]
        at org.h2.command.Parser.parseSelectUnion(Parser.java:2649) ~[h2-1.4.200.jar!/:na]
        at org.h2.command.Parser.parseQuery(Parser.java:2620) ~[h2-1.4.200.jar!/:na]
        at org.h2.command.Parser.parsePrepared(Parser.java:868) ~[h2-1.4.200.jar!/:na]
        at org.h2.command.Parser.parse(Parser.java:843) ~[h2-1.4.200.jar!/:na]
        at org.h2.command.Parser.parse(Parser.java:815) ~[h2-1.4.200.jar!/:na]
        at org.h2.command.Parser.prepareCommand(Parser.java:738) ~[h2-1.4.200.jar!/:na]
        at org.h2.engine.Session.prepareLocal(Session.java:657) ~[h2-1.4.200.jar!/:na]
        at org.h2.engine.Session.prepareCommand(Session.java:595) ~[h2-1.4.200.jar!/:na]
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235) ~[h2-1.4.200.jar!/:na]
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76) ~[h2-1.4.200.jar!/:na]
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352) ~[h2-1.4.200.jar!/:na]
        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[HikariCP-4.0.3.jar!/:na]
        at org.springframework.jdbc.core.JdbcTemplate$SimplePreparedStatementCreator.createPreparedStatement(JdbcTemplate.java:1645) ~[spring-jdbc-5.3.8.jar!/:5.3.8]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649) ~[spring-jdbc-5.3.8.jar!/:5.3.8]

Here is the application.properties file:

    spring.datasource.url=jdbc:h2:file:/tmp/h2-db
    spring.datasource.driverClassName=org.h2.Driver
    spring.datasource.username=sa
    spring.datasource.password=password
    spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
    spring.h2.console.enabled=true
    spring.jpa.generate-ddl=true
    spring.jpa.hibernate.ddl-auto=create
    spring.jpa.properties.hibernate.show_sql=true   
    spring.jpa.properties.hibernate.use_sql_comments=true
    spring.jpa.properties.hibernate.format_sql=true
    spring.datasource.intialization-mode=always

The schema doesn't seem to be created despite ddl-auto=create. Any suggestion please ?

Thanks.

**Comment by cppwfs** [comment]
Probably want to use `spring.batch.initialize-schema`. https://docs.spring.io/spring-boot/docs/2.1.18.RELEASE/reference/html/howto-database-initialization.html#howto-initialize-a-spring-batch-database

**Comment by Jesvin-Sam-Geoffrey-R** [comment]
spring.batch.jdbc.initialize-schema=always          
               adding this helped me.
