### ISSUE TITLE
native-image: Missing resource hints for schema definitions

### ISSUE THREAD

**Issue by mhalbritter** [spring-cloud/spring-cloud-task#849]
When running the native-image from the spring-native sample `cloud-task` on the `sb-3.0.x` branch, i get the following exception:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'taskRepositoryInitializer': Cannot read SQL script from class path resource [org/springframework/cloud/task/schema-h2.sql]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1752) ~[cloud-task:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:604) ~[cloud-task:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:526) ~[cloud-task:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[cloud-task:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[cloud-task:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[cloud-task:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[cloud-task:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:930) ~[cloud-task:6.0.0-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:926) ~[cloud-task:6.0.0-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:592) ~[cloud-task:6.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:735) ~[cloud-task:3.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:431) ~[cloud-task:3.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[cloud-task:3.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1307) ~[cloud-task:3.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1296) ~[cloud-task:3.0.0-SNAPSHOT]
	at com.example.task.TaskApplication.main(TaskApplication.java:22) ~[cloud-task:0.0.1-SNAPSHOT]
Caused by: org.springframework.jdbc.datasource.init.CannotReadScriptException: Cannot read SQL script from class path resource [org/springframework/cloud/task/schema-h2.sql]
	at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:239) ~[na:na]
	at org.springframework.jdbc.datasource.init.ResourceDatabasePopulator.populate(ResourceDatabasePopulator.java:254) ~[na:na]
	at org.springframework.jdbc.datasource.init.DatabasePopulatorUtils.execute(DatabasePopulatorUtils.java:54) ~[na:na]
	at org.springframework.cloud.task.repository.support.TaskRepositoryInitializer.afterPropertiesSet(TaskRepositoryInitializer.java:129) ~[cloud-task:3.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1798) ~[cloud-task:6.0.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1748) ~[cloud-task:6.0.0-SNAPSHOT]
	... 15 common frames omitted
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/cloud/task/schema-h2.sql] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:183) ~[cloud-task:6.0.0-SNAPSHOT]
	at org.springframework.core.io.support.EncodedResource.getReader(EncodedResource.java:146) ~[cloud-task:6.0.0-SNAPSHOT]
	at org.springframework.jdbc.datasource.init.ScriptUtils.readScript(ScriptUtils.java:328) ~[na:na]
	at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:236) ~[na:na]
	... 20 common frames omitted
```

I guess there's a resource hint missing.

**Comment by cppwfs** [comment]
Resolved with PR.
