### ISSUE TITLE
" java.lang.IllegalArgumentException: jobs must not be null nor empty" ERR and  launch on multiple servers issue.

### ISSUE THREAD

**Issue by heartsteer** [spring-cloud/spring-cloud-task#884]
1)Any idea what the root  cause of this err?    
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47) [test-batch-template-app-2.1.0-test.1.jar:?]
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:96) [test-batch-template-app-2.1.0-test.1.jar:?]
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:40) [test-batch-template-app-2.1.0-test.1.jar:?]
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:41) [test-batch-template-app-2.1.0-test.1.jar:?]
Caused by: java.lang.IllegalArgumentException: jobs must not be null nor empty

2)Another question is a  distributed environment, Can the master server  start the master on the master server and start the workers on respective slave server?

**Comment by cppwfs** [comment]
I can't tell much from this stack trace.   Is this the complete stack trace?   What version of task/batch/boot are you using?
