### ISSUE TITLE
Task error message - getting underlying message

### ISSUE THREAD

**Issue by zargarf** [spring-cloud/spring-cloud-task#890]
Hi

When an exception is thrown in my spring-cloud-task application that implements CommandRunner, the TaskListener I have created gets the exception. However the exception is always wrapped in an IllegalStateException: Failed to execute CommandLineRunner.

I would like to capture just the underlying reason for the failure. But if I extract this in the TaskListener onTaskFailed(taskExcecution, throwable) method and set the errorMessage on the TaskExecution object, it still gets persisted with the full original stack trace.

Is there any way to override the errorMessage in the TaskExecution object after a failure?

**TaskListener**
```
@Component
@Log4j2
public class TaskListener implements TaskExecutionListener 
{
@Override
  public void onTaskFailed(final TaskExecution taskExecution, final Throwable throwable) {
    log.error("Task {} failed with exception {}", taskExecution.getExternalExecutionId(), throwable);
    taskExecution.setExitMessage("Failed");
   var errorMessage =  unwrapped.getCause().toString();
log.info("Setting error message to {}, errorMessage);
    taskExecution.setErrorMessage(errorMessage);
    }

  }

```

**QueryRunner**
```
public class QueryRunner implements CommandLineRunner {

@Override
  public void run(String... args) throws Exception {   
   throw new RuntimeException("real exception message");
  }
}
```

Full Exception thrown in logs:
```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-2.7.7.jar!/:2.7.7]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752) ~[spring-boot-2.7.7.jar!/:2.7.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.7.7.jar!/:2.7.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.7.7.jar!/:2.7.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.7.7.jar!/:2.7.7]
	at io.task.query.Application.main(Application.java:23) ~[classes!/:local-SNAPSHOT]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[application.jar:local-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[application.jar:local-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[application.jar:local-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[application.jar:local-SNAPSHOT]
Caused by: java.lang.RuntimeException: real message
	at io.task.query.runner.QueryRunner.run(QueryRunner.java:106) ~[classes!/:local-SNAPSHOT]
	at org.springframework.cloud.sleuth.instrument.task.TraceCommandLineRunner.run(TraceCommandLineRunner.java:50) ~[spring-cloud-sleuth-instrumentation-3.1.5.jar!/:3.1.5]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768) ~[spring-boot-2.7.7.jar!/:2.7.7]
```

Log message in TaskListener:
```
Setting error message to java.lang.RuntimeException: real message
```

Error message in TaskExecution DB table:
```
java.lang.IllegalStateException: Failed to execute CommandLineRunner\n\tat org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)\n\tat org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:314)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)\n\tat io.task.query.Application.main(Application.java:23)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)\n\tat java.base/java.lang.reflect.Method.invoke(Unknown Source)\n\tat org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)\n\tat org.springframework.boot.loader.Launcher.launch(Launcher.java:108)\n\tat org.springframework.boot.loader.Launcher.launch(Launcher.java:58)\n\tat org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)\nCaused by: java.lang.RuntimeException: real message\n\tat io.task.query.runner.QueryRunner.run(QueryRunner.java:106)\n\tat org.springframework.cloud.sleuth.instrument.task.TraceCommandLineRunner.run(TraceCommandLineRunner.java:50)\n\tat org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768)\n\t... 11 more\n
```

I also note in the logs I get the following error printed - is this related to the attempted sending of the exception via an Event (I can get rid of the error by disabling task events in the app)?:
```
failed to convert object to Message; nested exception is org.springframework.messaging.MessagingException: At most one parameter (or expression via method-level @Payload) may be mapped to the payload or Message. Found more than one on method [public abstract void org.springframework.cloud.task.listener.TaskExecutionListener.onTaskFailed(org.springframework.cloud.task.repository.TaskExecution,java.lang.Throwable)] :While handling this error: java.lang.RuntimeException: real message

```
**Versions:**
spring-cloud-starter-task: 2.4.5
spring-cloud-starter-stream-rabbit: 3.2.6
spring-boot-starter-parent: 2.7.7
spring-cloud-starter-sleuth:jar:3.1.5

**Comment by cppwfs** [comment]
Hello @zargarf ,
Create your own `TaskRepository` by extending the `SimpleTaskRepository`.  In your TaskRepository update how you would like the data to be stored in the TaskExecution in the [completeTaskExecution](https://github.com/spring-cloud/spring-cloud-task/blob/2.4.x/spring-cloud-task-core/src/main/java/org/springframework/cloud/task/repository/support/SimpleTaskRepository.java#L100-L115) method.  
Then create your own TaskConfigurer bean that uses your TaskRepository.  You may do this by extending the `DefaultTaskConfigurer` and updating the constructor. This example maybe useful: https://github.com/spring-cloud/spring-cloud-task/blob/2.4.x/spring-cloud-task-samples/multiple-datasources/src/main/java/io/spring/configuration/CustomTaskConfigurer.java

And yes, by `setting spring_cloud_task_events_enabled=false` it will remove the `MessagingException` log message.
