### ISSUE TITLE
Composed Task - Error: 1364-HY000: Field 'CREATE_TIME' doesn't have a default value, individual tasks are working fine

### ISSUE THREAD

**Issue by mudduvenkatesh** [spring-cloud/spring-cloud-task#905]
[Data Flow](http://localhost:9393/dashboard/index.html#/)
Applications
Streams
Runtime
Tasks
Task executions
Job executions
Audit Records
Tools
Task execution - Execution ID: 68
Information
Execution Id
68
Arguments
df-transaction-id: 89xbr4thou1239
business-date: 2023-06-29
run-date: 2023-06-29
dataflow-spec: http://metadata.nppes.cms.org/dtco/systemdatainterfacespecification/hmWvM3DBqnAn
--spring.cloud.task.executionid: 68
--spring.cloud.data.flow.taskappname: composed-task-runner
External Execution Id
sdf-standard-dataunification-job-f4868f77-767d-4e7f-af85-b69aefd50be3
Batch Job
Job Execution Ids
43
Start Time
2023-06-30 09:17:51,000[-4]
End Time
2023-06-30 09:17:51,000[-4]
Duration
00:00:00.000
Exit Code
0
Exit Message
N/A
Resource URL
org.springframework.cloud:spring-cloud-dataflow-composed-task-runner:jar:2.10.3
Application Properties
management.metrics.tags.service: task-application
spring.datasource.username: ******
spring.datasource.url: ******
spring.datasource.driverClassName: org.mariadb.jdbc.Driver
management.metrics.tags.application: ${spring.cloud.task.name:unknown}-${spring.cloud.task.executionid:unknown}
platform-name: default
spring.cloud.task.name: sdf-standard-dataunification-job
graph: sdf-standard-dataunification-job-sdf-du-dl-task && sdf-standard-dataunification-job-sdf-du-dc-task && sdf-standard-dataunification-job-sdf-du-dv-task
spring.datasource.password: ******
Platform Properties
N/A
Task
Name
sdf-standard-dataunification-job
Description
sdf-standard-dataunification-job
Definition
sdf-du-dl-task && sdf-du-dc-task && sdf-du-dv-task
Status
ERROR
Applications
sdf-du-dl-task  sdf-du-dl-task
sdf-du-dc-task  sdf-du-dc-task
sdf-du-dv-task  sdf-du-dv-task
Beginning of Modal Content
Log task execution 68

stdout:
  _____                                         _   _______        _
 / ____|                                       | | |__   __|      | |
| |     ___  _ __ ___  _ __   ___  ___  ___  __| |    | | __ _ ___| | __
| |    / _ \| '_ ` _ \| '_ \ / _ \/ __|/ _ \/ _` |    | |/ _` / __| |/ /
| |___| (_) | | | | | | |_) | (_) \__ \  __/ (_| |    | | (_| \__ \   <
 \_____\___/|_| |_| |_| .__/ \___/|___/\___|\__,_|    |_|\__,_|___/_|\_\
                      | |
                      |_|
 _____
|  __ \
| |__) |   _ _ __  _ __   ___ _ __
|  _  / | | | '_ \| '_ \ / _ \ '__|
| | \ \ |_| | | | | | | |  __/ |
|_|  \_\__,_|_| |_|_| |_|\___|_|

2023-06-30 09:17:47.400  INFO 32338 --- [           main] o.s.c.d.c.ComposedTaskRunner             : Starting ComposedTaskRunner v2.10.3 using Java 17.0.6 on VenkateshMuddu-MBP with PID 32338 (/Users/venkateshmuddu/.m2/repository/org/springframework/cloud/spring-cloud-dataflow-composed-task-runner/2.10.3/spring-cloud-dataflow-composed-task-runner-2.10.3.jar started by venkateshmuddu in /private/var/folders/ss/6y0dj17d1bzffxghr9xvxlk40000gn/T/1543855324361564/sdf-standard-dataunification-job-f4868f77-767d-4e7f-af85-b69aefd50be3)
2023-06-30 09:17:47.405  INFO 32338 --- [           main] o.s.c.d.c.ComposedTaskRunner             : No active profile set, falling back to 1 default profile: "default"
2023-06-30 09:17:48.445  INFO 32338 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2023-06-30 09:17:48.455  INFO 32338 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2023-06-30 09:17:48.488  INFO 32338 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 17 ms. Found 0 JPA repository interfaces.
2023-06-30 09:17:48.853  INFO 32338 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.task.batch.configuration.TaskBatchAutoConfiguration' of type [org.springframework.cloud.task.batch.configuration.TaskBatchAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-06-30 09:17:49.160  INFO 32338 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2023-06-30 09:17:49.344  INFO 32338 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2023-06-30 09:17:49.459  INFO 32338 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2023-06-30 09:17:49.566  INFO 32338 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.6.15.Final
2023-06-30 09:17:49.848  INFO 32338 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2023-06-30 09:17:50.107  INFO 32338 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MariaDB53Dialect
2023-06-30 09:17:50.512  INFO 32338 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2023-06-30 09:17:50.530  INFO 32338 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2023-06-30 09:17:50.686  INFO 32338 --- [           main] o.s.b.c.r.s.JobRepositoryFactoryBean     : No database type set, using meta data indicating: MYSQL
2023-06-30 09:17:50.718  INFO 32338 --- [           main] o.s.b.c.r.s.JobRepositoryFactoryBean     : No database type set, using meta data indicating: MYSQL
2023-06-30 09:17:50.719  INFO 32338 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : No TaskExecutor has been set, defaulting to synchronous executor.
2023-06-30 09:17:50.961  WARN 32338 --- [           main] o.m.jdbc.message.server.ErrorPacket      : Error: 1050-42S01: Table 'task_execution' already exists
2023-06-30 09:17:50.963  WARN 32338 --- [           main] o.m.jdbc.message.server.ErrorPacket      : Error: 1050-42S01: Table 'task_execution_params' already exists
2023-06-30 09:17:50.964  WARN 32338 --- [           main] o.m.jdbc.message.server.ErrorPacket      : Error: 1050-42S01: Table 'task_task_batch' already exists
2023-06-30 09:17:50.964  WARN 32338 --- [           main] o.m.jdbc.message.server.ErrorPacket      : Error: 1050-42S01: Table 'task_seq' already exists
2023-06-30 09:17:50.966  WARN 32338 --- [           main] o.m.jdbc.message.server.ErrorPacket      : Error: 1062-23000: Duplicate entry '0' for key 'task_seq.UNIQUE_KEY_UN'
2023-06-30 09:17:50.967  WARN 32338 --- [           main] o.m.jdbc.message.server.ErrorPacket      : Error: 1050-42S01: Table 'task_lock' already exists
2023-06-30 09:17:51.190  INFO 32338 --- [           main] o.s.c.d.c.ComposedTaskRunner             : Started ComposedTaskRunner in 4.762 seconds (JVM running for 5.442)
2023-06-30 09:17:51.192  INFO 32338 --- [           main] o.s.b.a.b.JobLauncherApplicationRunner   : Running default command line with: [df-transaction-id=89xbr4thou1239, business-date=2023-06-29, run-date=2023-06-29, dataflow-spec=http://metadata.nppes.cms.org/dtco/systemdatainterfacespecification/hmWvM3DBqnAn]
2023-06-30 09:17:51.193  INFO 32338 --- [           main] o.s.b.c.r.s.JobRepositoryFactoryBean     : No database type set, using meta data indicating: MYSQL
2023-06-30 09:17:51.228  INFO 32338 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : Job: [FlowJob: [name=sdf-standard-dataunification-job]] launched with the following parameters: [{dataflow-spec=http://metadata.nppes.cms.org/dtco/systemdatainterfacespecification/hmWvM3DBqnAn, df-transaction-id=89xbr4thou1239, run.id=1, business-date=2023-06-29, run-date=2023-06-29}]
2023-06-30 09:17:51.238  INFO 32338 --- [           main] o.s.c.t.b.l.TaskBatchExecutionListener   : The job execution id[ 43 ](http://localhost:9393/dashboard/index.html#/tasks-jobs/job-executions/43)was run within the task execution 68
2023-06-30 09:17:51.249  WARN 32338 --- [           main] o.m.jdbc.message.server.ErrorPacket      : Error: 1364-HY000: Field 'CREATE_TIME' doesn't have a default value
2023-06-30 09:17:51.343 ERROR 32338 --- [           main] o.s.batch.core.job.AbstractJob           : Encountered fatal error executing job

org.springframework.batch.core.JobExecutionException: Flow execution ended unexpectedly
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:145) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:320) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:149) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50) ~[spring-core-5.3.27.jar!/:5.3.27]
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:140) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:128) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at jdk.proxy2/jdk.proxy2.$Proxy75.run(Unknown Source) ~[na:na]
	at org.springframework.boot.autoconfigure.batch.JobLauncherApplicationRunner.execute(JobLauncherApplicationRunner.java:199) ~[spring-boot-autoconfigure-2.7.11.jar!/:2.7.11]
	at org.springframework.boot.autoconfigure.batch.JobLauncherApplicationRunner.executeLocalJobs(JobLauncherApplicationRunner.java:173) ~[spring-boot-autoconfigure-2.7.11.jar!/:2.7.11]
	at org.springframework.boot.autoconfigure.batch.JobLauncherApplicationRunner.launchJobFromProperties(JobLauncherApplicationRunner.java:160) ~[spring-boot-autoconfigure-2.7.11.jar!/:2.7.11]
	at org.springframework.boot.autoconfigure.batch.JobLauncherApplicationRunner.run(JobLauncherApplicationRunner.java:155) ~[spring-boot-autoconfigure-2.7.11.jar!/:2.7.11]
	at org.springframework.boot.autoconfigure.batch.JobLauncherApplicationRunner.run(JobLauncherApplicationRunner.java:150) ~[spring-boot-autoconfigure-2.7.11.jar!/:2.7.11]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:759) ~[spring-boot-2.7.11.jar!/:2.7.11]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:749) ~[spring-boot-2.7.11.jar!/:2.7.11]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.7.11.jar!/:2.7.11]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.7.11.jar!/:2.7.11]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.7.11.jar!/:2.7.11]
	at org.springframework.cloud.dataflow.composedtaskrunner.ComposedTaskRunner.main(ComposedTaskRunner.java:31) ~[classes!/:2.10.3]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[spring-cloud-dataflow-composed-task-runner-2.10.3.jar:2.10.3]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[spring-cloud-dataflow-composed-task-runner-2.10.3.jar:2.10.3]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[spring-cloud-dataflow-composed-task-runner-2.10.3.jar:2.10.3]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[spring-cloud-dataflow-composed-task-runner-2.10.3.jar:2.10.3]
Caused by: org.springframework.batch.core.job.flow.FlowExecutionException: Ended flow=sdf-standard-dataunification-job-sdf-du-dl-task_0 at state=sdf-standard-dataunification-job-sdf-du-dl-task_0.step0 with exception
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:178) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	at org.springframework.batch.core.job.flow.support.state.FlowState.handle(FlowState.java:56) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:139) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	... 34 common frames omitted
Caused by: org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [INSERT into BATCH_STEP_EXECUTION(STEP_EXECUTION_ID, VERSION, STEP_NAME, JOB_EXECUTION_ID, START_TIME, END_TIME, STATUS, COMMIT_COUNT, READ_COUNT, FILTER_COUNT, WRITE_COUNT, EXIT_CODE, EXIT_MESSAGE, READ_SKIP_COUNT, WRITE_SKIP_COUNT, PROCESS_SKIP_COUNT, ROLLBACK_COUNT, LAST_UPDATED) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; (conn=5166) Field 'CREATE_TIME' doesn't have a default value; nested exception is java.sql.SQLException: (conn=5166) Field 'CREATE_TIME' doesn't have a default value
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:251) ~[spring-jdbc-5.3.27.jar!/:5.3.27]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70) ~[spring-jdbc-5.3.27.jar!/:5.3.27]
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541) ~[spring-jdbc-5.3.27.jar!/:5.3.27]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667) ~[spring-jdbc-5.3.27.jar!/:5.3.27]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960) ~[spring-jdbc-5.3.27.jar!/:5.3.27]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1015) ~[spring-jdbc-5.3.27.jar!/:5.3.27]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1020) ~[spring-jdbc-5.3.27.jar!/:5.3.27]
	at org.springframework.batch.core.repository.dao.JdbcStepExecutionDao.saveStepExecution(JdbcStepExecutionDao.java:154) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	at org.springframework.batch.core.repository.support.SimpleJobRepository.add(SimpleJobRepository.java:189) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.27.jar!/:5.3.27]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.27.jar!/:5.3.27]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.27.jar!/:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at jdk.proxy2/jdk.proxy2.$Proxy72.add(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:128) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220) ~[spring-aop-5.3.27.jar!/:5.3.27]
	at jdk.proxy2/jdk.proxy2.$Proxy72.add(Unknown Source) ~[na:na]
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:146) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169) ~[spring-batch-core-4.3.8.jar!/:4.3.8]
	... 39 common frames omitted
Caused by: java.sql.SQLException: (conn=5166) Field 'CREATE_TIME' doesn't have a default value
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:299) ~[mariadb-java-client-3.1.4.jar!/:na]
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370) ~[mariadb-java-client-3.1.4.jar!/:na]
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:134) ~[mariadb-java-client-3.1.4.jar!/:na]
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:872) ~[mariadb-java-client-3.1.4.jar!/:na]
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:811) ~[mariadb-java-client-3.1.4.jar!/:na]
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:730) ~[mariadb-java-client-3.1.4.jar!/:na]
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:654) ~[mariadb-java-client-3.1.4.jar!/:na]
	at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:95) ~[mariadb-java-client-3.1.4.jar!/:na]
	at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:334) ~[mariadb-java-client-3.1.4.jar!/:na]
	at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:311) ~[mariadb-java-client-3.1.4.jar!/:na]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-4.0.3.jar!/:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar!/:na]
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$2(JdbcTemplate.java:965) ~[spring-jdbc-5.3.27.jar!/:5.3.27]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651) ~[spring-jdbc-5.3.27.jar!/:5.3.27]
	... 72 common frames omitted

2023-06-30 09:17:51.352  INFO 32338 --- [           main] o.s.b.c.l.support.SimpleJobLauncher      : Job: [FlowJob: [name=sdf-standard-dataunification-job]] completed with the following parameters: [{dataflow-spec=http://metadata.nppes.cms.org/dtco/systemdatainterfacespecification/hmWvM3DBqnAn, df-transaction-id=89xbr4thou1239, run.id=1, business-date=2023-06-29, run-date=2023-06-29}] and the following status: [FAILED] in 117ms
2023-06-30 09:17:51.362  INFO 32338 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2023-06-30 09:17:51.366  INFO 32338 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2023-06-30 09:17:51.372  INFO 32338 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

End of Modal Content

**Comment by mudduvenkatesh** [comment]
I made the following changes to make the composed task work
ALTER TABLE `sdf_task_repo`.`BATCH_JOB_EXECUTION_PARAMS` 
ADD COLUMN `TYPE_CD` VARCHAR(6) NULL AFTER `IDENTIFYING`,
ADD COLUMN `KEY_NAME` VARCHAR(100) NULL AFTER `TYPE_CD`,
ADD COLUMN `STRING_VAL` VARCHAR(250) NULL AFTER `KEY_NAME`,
ADD COLUMN `DATE_VAL` DATETIME NULL AFTER `STRING_VAL`,
ADD COLUMN `LONG_VAL` INT NULL AFTER `DATE_VAL`,
ADD COLUMN `DOUBLE_VAL` DOUBLE NULL AFTER `LONG_VAL`;

Error: 1364-HY000: Field 'PARAMETER_NAME' doesn't have a default value
2023-06-30 09:15:56.464  INFO 32284 --- [           main] ConditionEvaluationReportLoggingListener : 

ALTER TABLE `sdf_task_repo`.`BATCH_JOB_EXECUTION_PARAMS` 
CHANGE COLUMN `PARAMETER_NAME` `PARAMETER_NAME` VARCHAR(100) NOT NULL DEFAULT 'PNAME1' ,
CHANGE COLUMN `PARAMETER_TYPE` `PARAMETER_TYPE` VARCHAR(100) NOT NULL DEFAULT 'PTYPE1' ;

ALTER TABLE `sdf_task_repo`.`BATCH_JOB_EXECUTION` 
CHANGE COLUMN `CREATE_TIME` `CREATE_TIME` DATETIME(6) NOT NULL DEFAULT '1970-01-01 00:00:00'; ;

ALTER TABLE `sdf_task_repo`.`BATCH_STEP_EXECUTION` 
CHANGE COLUMN `CREATE_TIME` `CREATE_TIME` DATETIME(6) NOT NULL DEFAULT 
'1970-01-01 00:00:00' ;

**Comment by cppwfs** [comment]
This is the incorrect forum for Composed Task Questions.   Please open an issue on the SCDF project https://github.com/spring-cloud/spring-cloud-dataflow.
