### ISSUE TITLE
BOOT3 tables not used

### ISSUE THREAD

**Issue by Gunthervg** [spring-cloud/spring-cloud-task#929]
We recently migrated our containers from Spring boot v2.x to v3.x which created the boot3_ db tables.
When executing a container it seems that it still uses the old tables from v2:

<pre><code>
Caused by: java.sql.SQLSyntaxErrorException: (conn=414700) 'dataplatform_server.TASK_SEQ' is not a SEQUENCE
    at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:282) ~[mariadb-java-client-3.1.4.jar:?]
    at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370) ~[mariadb-java-client-3.1.4.jar:?]
    at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:134) ~[mariadb-java-client-3.1.4.jar:?]
    at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:872) ~[mariadb-java-client-3.1.4.jar:?]
    at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:811) ~[mariadb-java-client-3.1.4.jar:?]
    at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:730) ~[mariadb-java-client-3.1.4.jar:?]
    at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:654) ~[mariadb-java-client-3.1.4.jar:?]
    at org.mariadb.jdbc.Statement.executeInternal(Statement.java:957) ~[mariadb-java-client-3.1.4.jar:?]
    at org.mariadb.jdbc.Statement.executeQuery(Statement.java:147) ~[mariadb-java-client-3.1.4.jar:?]
    at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:110) ~[HikariCP-5.0.1.jar:?]
    at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java) ~[HikariCP-5.0.1.jar:?]
    at org.springframework.jdbc.support.incrementer.AbstractSequenceMaxValueIncrementer.getNextKey(AbstractSequenceMaxValueIncrementer.java:70) ~[spring-jdbc-6.0.12.jar:6.0.12]
    at org.springframework.jdbc.support.incrementer.AbstractDataFieldMaxValueIncrementer.nextLongValue(AbstractDataFieldMaxValueIncrementer.java:128) ~[spring-jdbc-6.0.12.jar:6.0.12]
    at org.springframework.cloud.task.repository.dao.JdbcTaskExecutionDao.getNextExecutionId(JdbcTaskExecutionDao.java:432) ~[spring-cloud-task-core-3.0.3.jar:3.0.3]
    at org.springframework.cloud.task.repository.dao.JdbcTaskExecutionDao.createTaskExecution(JdbcTaskExecutionDao.java:211) ~[spring-cloud-task-core-3.0.3.jar:3.0.3]
    at org.springframework.cloud.task.repository.support.SimpleTaskRepository.createTaskExecution(SimpleTaskRepository.java:115) ~[spring-cloud-task-core-3.0.3.jar:3.0.3]
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-6.0.12.jar:6.0.12]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.0.12.jar:6.0.12]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.0.12.jar:6.0.12]
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) ~[spring-aop-6.0.12.jar:6.0.12]
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-6.0.12.jar:6.0.12]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391) ~[spring-tx-6.0.12.jar:6.0.12]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.0.12.jar:6.0.12]
</code></pre>

**Comment by cppwfs** [comment]
Thank you for opening the issue.   But we need some details so that we can assist you.   
Can you share with me the following:
* The steps to reproduce?
* The environment properties (cleansed) that you set when you launched the task?
* The versions of task and boot you are using?
Also, are you launching the app using Spring Cloud Data Flow?

**Comment by Gunthervg** [comment]
@cppwfs 

Steps to reproduce: 
- Create a task with Spring Boot Starter Parent 2.7.17 and run it on SCDF
- Upgrade the task to Spring Boot Starter Parent 3.1.4 and run it again on SCDF => exception from stacktrace

Env properties:
Picked up JAVA_TOOL_OPTIONS: -Djava.security.properties=/layers/paketo-buildpacks_bellsoft-liberica/java-security-properties/java-security.properties -XX:+ExitOnOutOfMemoryError -XX:ActiveProcessorCount=4 -XX:MaxDirectMemorySize=10M -Xmx605728K -XX:MaxMetaspaceSize=135647K -XX:ReservedCodeCacheSize=240M -Xss1M -XX:+UnlockDiagnosticVMOptions -XX:NativeMemoryTracking=summary -XX:+PrintNMTStatistics -Dorg.springframework.cloud.bindings.boot.enable=true

I think this has something to do with following instructions:
https://github.com/spring-cloud/spring-cloud-task/wiki/Spring-Cloud-Task-3.0-Migration-Guide

_Up until v2, the DDL script for MS SQLServer used tables to emulate sequences. In this version, this usage has been updated with real sequences:_

Together with this change on SCDF
https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_spring_cloud_task_batch_applications

... 

Seems we missed the following important change:

_In order to know that the specific task is a Boot 3.x application the version will have to be provided as part of registration. The rest endpoints accepts a bootVersion=3 parameter and the shell commands accepts --bootVersion 3_
